version: '3'

networks:
  custom_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  db:
    image: postgres:15
    container_name: postgresql-15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cm6
    networks:
      custom_network:
        ipv4_address: 172.18.0.2
    ports:
      - "5433:5432"

  run:
    image: debian:latest
    container_name: run
    restart: always
    networks:
      custom_network:
        ipv4_address: 172.18.0.3
    command: |
      sh -c "
        # Добавляем строки в /etc/environment
        if [ -f /etc/environment ]; then
          sed -i '/^http_proxy/d' /etc/environment || true
          echo 'http_proxy="http://172.16.1.10:3128"' >> /etc/environment
          sed -i '/^https_proxy/d' /etc/environment || true
          echo 'https_proxy="http://172.16.1.10:3128"' >> /etc/environment
        fi
        # Добавляем строки в /etc/apt/apt.conf.d/05proxy
        if [ -f /etc/apt/apt.conf.d/05proxy ]; then
          sed -i '/^http_proxy/d' /etc/apt/apt.conf.d/05proxy || true
          echo 'Acquire::http::Proxy "http://172.16.1.10:3128";' >> /etc/apt/apt.conf.d/05proxy
        fi
        # Переводим контейнер в спящий режим, чтобы он не завершался
        sleep infinity
      "