services:

  db:
    image: postgres:15
    container_name: postgresql-15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - '81:8080'